[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
GaussianFermions = "2621d614-78f7-4793-80a6-586747345a0a"
ITensorFormatter = "b6bf39f1-c9d3-4bad-aad8-593d802f65fd"

[sources.GaussianFermions]
path = ".."

[compat]
Documenter = "1"
GaussianFermions = "0.1"
ITensorFormatter = "0.2.27"
